spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testdb?useSSL=false
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456


    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    servlet:
        context-path: /blog
    port: 8088